spring:
  # MySQL connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CLEARDB_DATABASE_USERNAME:root}
    password: ${CLEARDB_DATABASE_PASSWORD:mypassword}
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:52000/food_truck_finder}?createDatabaseIfNotExist=true&useSSL=false
  # Log JPA queries
  # Comment this in production
  jpa:
    show-sql: true
    # Drop and create new tables (create, create-drop, validate, update)
    # Only for testing purpose - comment this in production
    hibernate:
      ddl-auto: update
    # Hibernate SQL dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port : 8080